server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location ^~ /apps/ {
    return 308 https://products.altacod.com$request_uri;
  }

  location / {
    try_files $uri/index.html $uri /index.html;
  }
}
